# usingDefaultConfig
# true : will use default config, which spawns 1 to 3 feather per egg spawn.
# false: use false when you want to change featherAmount to your own custom amount.
usingDefaultConfig: true

# maxFeatherAmount is the maximum amount of feather a egg spawn can trigger.
# If set to 1, it will be between 1 and 1 feather.
# If set to 10, it will be between 1 to 10 feathers.

# WARNING ---- Setting the max amount of feather above anything more than
# 15 or 20 could have huge performance impacts on your server if a player
# owns a big chicken farm. Considered yourself warned ---- WARNING.
maxFeatherAmount: 3
